# Site Settings
encoding: UTF-8
exclude:
  [
    '*.gem',
    '*.gemspec',
    'doc',
    'docs',
    'Gemfile',
    'Gemfile.lock',
    'node_modules',
    'Rakefile',
    'starter-kit',
    'v191211.github.io',
    'vendor',
  ]
lang: zh
permalink: /:year/:month/:day/:title/
theme: jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "assets/**/*.*"
    values:
      sitemap: false

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ['apos', 'apos', 'quot', 'quot']
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://empvalley.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: 晨霜’s Blog
description: '晨霜的个人 blog，软件开发，深圳。'
keywords: '软件，工程师，测试，全栈，深圳'
author:
  name: 晨霜
  job_title: 软件开发
  location: 深圳
  # email: empvalley@empvalley.com
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/v191211/
    # - name: instagram
    #   url: https://www.instagram.com/191211
    - name: linkedin
      url: https://www.linkedin.com/in/fighting-v/
    - name: stackoverflow
      url: https://stackoverflow.com/users/4612522/adam-smith
    - name: twitter
      url:
    # - name: vk
    #   url: https://vk.com/fighting_vvv
home:
  section1:
  section2:
  section3:
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License
  cc_license_image: /assets/images/theme/cc-by-sa.png # Choose one at https://creativecommons.org/choose/
  footer_content: 晨霜，软件开发，深圳

disqus:
  shortname: fighting-v
  public_key: CefuUqy9qWjTPQyiiLRTCFkFAOl7FIXLjBHyIdpFqMFDFYgqYgOHvaJIZXybCUV4
google_tag_manager: 'GTM-WLHQF68'
addthis_public_id: ra-5fd67ed699f02738 # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
